baseURL = "https://rannndoms.pages.dev/"
title = "Rannndoms®"
theme = "hugo-bearblog"

[params]
  description = "Catatan acak dari Android"
  author = "Rannndoms"

[markup]
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
