baseURL = "https://rannndoms.pages.dev/"
title = "Rannndoms®"
theme = "hugo-bearblog"
buildFuture = true
disableHugoGeneratorInject = true

[params]
  description = "Tulisan pendek tentang apa pun yang sedang menarik perhatian"
  author = "Rannndoms"

[markup]
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
